name: build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Test
        run: go test -v ./...

      - name: Run staticcheck linter
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2024.1.1"
          install-go: false