name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    uses: tedpearson/nw-updater/.github/workflows/release-template.yaml@main
    with:
      executable: nw-updater
      ref: main